name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'COPYING'
      - '*.txt'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'COPYING'
      - '*.txt'
      - '*.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install SDL2 and ffplay
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev ffmpeg
      - name: Install Dependencies
        run: go mod tidy
      - name: Build and test with SDL2
        run: |
          go build ./...
          go test ./... -v
      - name: Build and test with ffplay
        run: |
          go build -tags ff ./...
          go test -tags ff ./... -v
